version: '3.8'
services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=SecurePassword123
      - POSTGRES_DB=travel-plan
    volumes:
      - travel-plan:/var/lib/postgresql/data
    ports:
      - '5432:5432'

volumes:
  travel-plan: